CREATE DATABASE ${db.name} WITH OWNER=${db.username.dev} ENCODING='UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TABLESPACE=pg_default;
CREATE DATABASE ${db.name} WITH OWNER=${db.username.dev} ENCODING='UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TABLESPACE=pg_default;
CREATE USER ${db.customer.service.user} WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${db.customer.service.password}';
CREATE USER ${db.inventory.service.user} WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${db.inventory.service.password}';
CREATE USER ${db.order.service.user} WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${db.order.service.password}';
CREATE USER ${db.supplier.service.user} WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${db.supplier.service.password}';

