CREATE DATABASE ${db.name} WITH OWNER=postgres ENCODING='UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TABLESPACE=pg_default;
CREATE DATABASE ${db.name} WITH OWNER=postgres ENCODING='UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TABLESPACE=pg_default;
CREATE USER customer_service_app WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '123hopS';
CREATE USER inventory_service_app WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '123hopS';
CREATE USER order_service_app WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '123hopS';
CREATE USER supplier_service_app WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '123hopS';

